import { useEffect } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import MobileCTA from "@/components/MobileCTA";

const Terms = () => {
  useEffect(() => {
    document.title = "Terms of Service | NoteNest";
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute("content", "Terms of Service for NoteNest. Read the rules and guidelines for using our educational platform.");
    }
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <Navbar />
      <main className="flex-1 container max-w-4xl mx-auto px-4 py-12 mt-20">
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        <div className="prose prose-lg dark:prose-invert max-w-none text-muted-foreground">
          <p className="font-semibold text-foreground">Last updated: July 2026</p>
          
          <h2 className="text-2xl font-bold mt-8 mb-4 text-foreground">1. Introduction</h2>
          <p>Welcome to NoteNest. These Terms of Service govern your access to and use of the NoteNest mobile application, website, and related services. By accessing or using our platform, you agree to be bound by these Terms.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4 text-foreground">2. Eligibility</h2>
          <p>You must be at least 13 years old to use NoteNest. If you are under 18, you may only use our paid services (such as purchasing credits or subscriptions) with the involvement and consent of a parent or legal guardian.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4 text-foreground">3. User Accounts</h2>
          <p>To access certain features, you must create an account via Email or Google OAuth. You are responsible for safeguarding your account credentials and for all activities that occur under your account. You must provide accurate and complete information during registration.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4 text-foreground">4. Acceptable Use</h2>
          <p>You agree not to use NoteNest to:</p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li>Upload or share unlawful, harmful, or abusive content.</li>
            <li>Violate the intellectual property rights of others.</li>
            <li>Attempt to bypass our security measures or rate limits.</li>
            <li>Use the AI generation features for malicious purposes, cheating, or generating prohibited content.</li>
          </ul>

          <h2 className="text-2xl font-bold mt-8 mb-4 text-foreground">5. AI-Generated Content Disclaimer</h2>
          <p>NoteNest utilizes Artificial Intelligence (including Google Gemini and Groq) to generate study notes, summaries, and chat responses. While we strive for accuracy, AI-generated content may occasionally be incorrect, incomplete, or misleading. You are responsible for verifying any information generated by our platform before relying on it for academic or professional purposes.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4 text-foreground">6. User-Uploaded Content</h2>
          <p>You retain ownership of the files, images, and text you upload to NoteNest. By uploading content, you grant NoteNest a non-exclusive license to store, process, and transmit this content to our cloud storage (AWS S3) and AI partners for the sole purpose of providing the service to you.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4 text-foreground">7. Subscription and Payments</h2>
          <p>NoteNest offers one-time credit purchases and recurring subscriptions via our payment partners (Paystack and Flutterwave). All payments are subject to the terms of these third-party processors. NoteNest does not store your raw credit card information. Fees are non-refundable except as required by law.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4 text-foreground">8. Intellectual Property</h2>
          <p>The NoteNest application, website, branding, and original content are the exclusive property of NoteNest and its licensors. You may not copy, modify, or distribute our proprietary software or designs without explicit permission.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4 text-foreground">9. Termination</h2>
          <p>We reserve the right to suspend or terminate your account at our discretion, without notice, if we determine that you have violated these Terms of Service or engaged in fraudulent activity.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4 text-foreground">10. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, NoteNest and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service, including data loss or academic consequences.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4 text-foreground">11. Disclaimer of Warranties</h2>
          <p>NoteNest is provided on an "AS IS" and "AS AVAILABLE" basis. We disclaim all warranties, express or implied, including the implied warranties of merchantability and fitness for a particular purpose.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4 text-foreground">12. Governing Law</h2>
          <p>These Terms shall be governed by and construed in accordance with applicable laws, without regard to its conflict of law provisions.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4 text-foreground">13. Contact Information</h2>
          <p>If you have any questions or concerns regarding these Terms of Service, please contact us at: <strong className="text-foreground">notenest.app1@gmail.com</strong>.</p>
        </div>
      </main>
      <Footer />
      <MobileCTA />
    </div>
  );
};

export default Terms;
